//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriaSoft.AspNet.Identity.DbFirst.Data
{
    using System;
    using System.Collections.Generic;
    
    using KriaSoft.AspNet.Identity.EntityFramework;
    
    public partial class UserClaim : IdentityClaim<int>
    {
    
        public virtual User User { get; set; }
    }
}
